{
  const ARMOR_MODEL      	armor/p_helmets.mdl
  const ARMOR_BODY		4
  const ARMOR_TEXT		"You put on a dark platemail helmet."
  const BARMOR_TYPE		platemail
  const BARMOR_PROTECTION	60%
	const STUN_PROTECTION 45

  const ARMOR_STR_REQ 20
}

#include items/armor_base_helmet

{  game_spawn

   name 	a|Darkened Steel Helmet
   desc 	"A powerful helmet of blackened steel."
   weight 	45
   size     35
   wearable 1 head
   value    1150
   
   sethudsprite trade 85
}
